In [3]:
import numpy as np
import matplotlib.pyplot as plt 
import tensorflow as tf
import keras
from keras  import models, layers, optimizers

Using TensorFlow backend.


In [4]:
#Complete this function for creating  keras layer based on netwrok parameters, and run for each optimzer passed in the param
def mainDriverMNistKeras(opt):
    (x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()
    x_train = x_train.reshape(x_train.shape[0], x_train.shape[1]*x_train.shape[2])
    x_train = x_train/255
    x_test = x_test.reshape(x_test.shape[0], x_test.shape[1]*x_test.shape[2])
    x_test = x_test/255

    y_train_cat = keras.utils.to_categorical(y_train, num_classes=10)
    y_test_cat = keras.utils.to_categorical(y_test, num_classes=10)

    #Assume you have 3 layers, with 600 units inlayer1, 40 in layer 2, and 10 in layer 3, act=relu, relu, softmax, input shape same
    ## Write code to create this model (4 lines of code)
    network = models.Sequential()
    network.add(layers.Dense(600, activation="relu", input_shape =x_train.shape[1:]))
    network.add(layers.Dense(40, activation="relu"))
    network.add(layers.Dense(10, activation="softmax"))
    ## Write code to create this model (4 lines of code)
    ## Now take each optimizer passed in the parameter opt and run the model.
    ## We need to get the optimizer used and the accuracy for that optimzer
    ## Store the performance in a dictionary
    
    
    OptPerf = {}
    #Write Code to take each optimizer, compile, fit, predict for train and test and store the result in a dictionary OptPerf
    for i,op in opt.items():
        network.compile(optimizer= op, loss = "categorical_crossentropy", metrics = ["accuracy"])
        network.fit(x_train, y_train_cat, epochs=3, batch_size=1024)
        #use loss = "categorical_crossentropy", metrics = "accuracy" (in a list)
        y_pred_train = network.predict(x_train)
        y_pred_train_val = np.argmax(y_pred_train, axis=1)
        result_train=(y_pred_train_val == y_train)
        y_pred_test = network.predict(x_test)
        y_pred_test_val = np.argmax(y_pred_test, axis=1)
        result_test=(y_pred_test_val == y_test)
        
        
        OptPerf[i]={"train:" :np.sum(result_train)/len(result_train), "test:" : np.sum(result_test)/len(result_test)}
        print ("Over RESULTS", OptPerf)
    return (y_pred_test_val,y_test,y_pred_test)
    

In [5]:
#Call this with Rmsprop use optimizers.RMSprop(lr=0.001), and use "rmsprop" as another entry to identify that the result is for rmsprop
##One line of code
a=mainDriverMNistKeras({"Rmsprop": optimizers.RMSprop(lr=0.001)})

Epoch 1/3
60000/60000 [==============================] - 18s 308us/step - loss: 0.5785 - acc: 0.8311
Epoch 2/3
60000/60000 [==============================] - 18s 307us/step - loss: 0.2325 - acc: 0.9320
Epoch 3/3
60000/60000 [==============================] - 18s 307us/step - loss: 0.1586 - acc: 0.9534
Over RESULTS {'Rmsprop': {'train:': 0.9583833333333334, 'test:': 0.9544}}


In [6]:
#Good practice to have this protection block to accidentally prevent executing main code
if __name__ == "__main__":
    ## Now set the parameters for opt, and call the keras model to predict and store the prediction accuracy
#    "Rmsprop" = optimizers.RMSprop(lr=0.001)
#    "adadelta" = optimizers.adadelta()
#    "adagrad" = optimizers.adagrad(), ),
#    "adam" =  optimizers.adam(), ,),
#    "adamax"= optimizers.adamax(), ),
#    "nadam"= optimizers.nadam(), ),
#    "sgd"= optimizers.sgd(), )]
 #call and make predictions and store the accuracy for each optimizer
    optm=mainDriverMNistKeras({  "nadam":optimizers.nadam(),"sgd": optimizers.sgd(),"Rmsprop": optimizers.RMSprop(lr=0.001),"adadelta" :optimizers.adadelta(),"adagrad": optimizers.adagrad(),"adam": optimizers.adam(),"adamax":optimizers.adamax()})

Epoch 1/3
60000/60000 [==============================] - 20s 331us/step - loss: 0.4967 - acc: 0.8531
Epoch 2/3
60000/60000 [==============================] - 19s 315us/step - loss: 0.1583 - acc: 0.9541
Epoch 3/3
60000/60000 [==============================] - 19s 317us/step - loss: 0.1099 - acc: 0.9680
Over RESULTS {'nadam': {'train:': 0.9754, 'test:': 0.9674}}
Epoch 1/3
60000/60000 [==============================] - 18s 301us/step - loss: 0.0779 - acc: 0.9781
Epoch 2/3
60000/60000 [==============================] - 18s 297us/step - loss: 0.0741 - acc: 0.9790
Epoch 3/3
60000/60000 [==============================] - 18s 298us/step - loss: 0.0732 - acc: 0.9791
Over RESULTS {'nadam': {'train:': 0.9754, 'test:': 0.9674}, 'sgd': {'train:': 0.9795, 'test:': 0.9718}}
Epoch 1/3
60000/60000 [==============================] - 19s 311us/step - loss: 0.1001 - acc: 0.9694
Epoch 2/3
60000/60000 [==============================] - 18s 303us/step - loss: 0.0752 - acc: 0.9773
Epoch 3/3
60000/60000 [=====

In [9]:
import pandas as pd
df=pd.DataFrame(optm)

array([7, 2, 1, ..., 4, 5, 6])

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

array([1.0067394e-05, 3.2666574e-07, 1.1429262e-03, 3.1056919e-04,
       1.9263761e-07, 3.8181793e-06, 1.0566357e-07, 9.9840838e-01,
       5.9304402e-06, 1.1777449e-04], dtype=float32)

In [ ]:
df=pd.DataFrame(optm)

In [ ]:
df